### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by GarvanDigital** [contentstack/marketplace-app-boilerplate#11] opened 2022-11-01 06:57 UTC
I'm unable to resolve dependencies when installing:

 ```
 npm ERR! code ERESOLVE
[2022-11-01 08:53:10] │ npm ERR! ERESOLVE could not resolve
[2022-11-01 08:53:10] │ npm ERR! 
[2022-11-01 08:53:10] │ npm ERR! While resolving: @contentstack/venus-components@1.0.5
[2022-11-01 08:53:10] │ npm ERR! Found: react@18.2.0
[2022-11-01 08:53:10] │ npm ERR! node_modules/react
[2022-11-01 08:53:10] │ npm ERR!   react@"^18.2.0" from the root project
[2022-11-01 08:53:10] │ npm ERR!   peer react@">=16.3.0" from @emotion/core@10.3.1
[2022-11-01 08:53:10] │ npm ERR!   node_modules/@emotion/core
[2022-11-01 08:53:10] │ npm ERR!     @emotion/core@"^10.0.9" from react-select@3.2.0
[2022-11-01 08:53:10] │ npm ERR!     node_modules/@contentstack/venus-components/node_modules/react-select
[2022-11-01 08:53:10] │ npm ERR!       react-select@"^3.2.0" from @contentstack/venus-components@1.0.5
[2022-11-01 08:53:10] │ npm ERR!       node_modules/@contentstack/venus-components
[2022-11-01 08:53:10] │ npm ERR!         @contentstack/venus-components@"^1.0.4" from the root project
[2022-11-01 08:53:10] │ npm ERR!       1 more (react-select-async-paginate)
[2022-11-01 08:53:10] │ npm ERR!     peer @emotion/core@"^10.0.27" from @emotion/styled@10.3.0
[2022-11-01 08:53:10] │ npm ERR!     node_modules/@emotion/styled
[2022-11-01 08:53:10] │ npm ERR!       @emotion/styled@"^10.0.10" from react-treebeard@3.2.4
[2022-11-01 08:53:10] │ npm ERR!       node_modules/react-treebeard
[2022-11-01 08:53:10] │ npm ERR!         react-treebeard@"^3.2.4" from @contentstack/venus-components@1.0.5
[2022-11-01 08:53:10] │ npm ERR!         node_modules/@contentstack/venus-components
[2022-11-01 08:53:10] │ npm ERR!     2 more (@emotion/styled-base, react-treebeard)
[2022-11-01 08:53:10] │ npm ERR!   40 more (@emotion/styled, @emotion/styled-base, ...)
[2022-11-01 08:53:10] │ npm ERR! 
[2022-11-01 08:53:10] │ npm ERR! Could not resolve dependency:
[2022-11-01 08:53:10] │ npm ERR! peer react@"^16.8.6 || ^17.0.0" from @contentstack/venus-components@1.0.5
[2022-11-01 08:53:10] │ npm ERR! node_modules/@contentstack/venus-components
[2022-11-01 08:53:10] │ npm ERR!   @contentstack/venus-components@"^1.0.4" from the root project
[2022-11-01 08:53:10] │ npm ERR! 
[2022-11-01 08:53:10] │ npm ERR! Conflicting peer dependency: react@17.0.2
[2022-11-01 08:53:10] │ npm ERR! node_modules/react
[2022-11-01 08:53:10] │ npm ERR!   peer react@"^16.8.6 || ^17.0.0" from @contentstack/venus-components@1.0.5
[2022-11-01 08:53:10] │ npm ERR!   node_modules/@contentstack/venus-components
[2022-11-01 08:53:10] │ npm ERR!     @contentstack/venus-components@"^1.0.4" from the root project
[2022-11-01 08:53:10] │ npm ERR! 
[2022-11-01 08:53:10] │ npm ERR! Fix the upstream dependency conflict, or retry
[2022-11-01 08:53:10] │ npm ERR! this command with --force, or --legacy-peer-deps
[2022-11-01 08:53:10] │ npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[2022-11-01 08:53:10] │ npm ERR! 
[2022-11-01 08:53:10] │ npm ERR! See /home/apps/.npm/eresolve-report.txt for a full report.
[2022-11-01 08:53:10] │ 
[2022-11-01 08:53:10] │ npm ERR! A complete log of this run can be found in:
[2022-11-01 08:53:10] │ npm ERR!     /home/apps/.npm/_logs/2022-11-01T08_53_05_853Z-debug-0.log
[2022-11-01 08:53:10] │ 
[2022-11-01 08:53:10] │ unable to invoke layer creator
[2022-11-01 08:53:10] │ installing node_modules: exit status 1
[2022-11-01 08:53:10] │ ERROR: failed to build: exit status 1
```

**Comment by abhishek305** [comment] 2022-11-04 13:29
Hi @GarvanDigital,
Could you please provide steps to reproduce this issue?
Also would like to know which node version are you using.
Thanks !!

**Comment by Contentstack-AnkitaD** [comment] 2023-07-07 11:03
This issue seems to be related to conflicting peer dependencies with React. 
However, it's worth noting that this problem was addressed and resolved in our previous releases. 
The conflicting dependencies were subsequently updated and aligned to ensure compatibility. 

We recommend updating to the latest version of our package to avoid this issue. 
If you are still experiencing any difficulties, please let us know and we'll be happy to assist further.

Hence Closing this issue.

**Closed by Contentstack-AnkitaD** 2023-07-07 11:03 UTC
